# dcape-app-powerdns Makefile

SHELL               = /bin/sh
CFG                ?= .env

# Stats site host
APP_SITE           ?= ns.dev.lan

# App names (db/user name etc)
APP_NAME           ?= pdns-admin

# PgSQL used as DB
USE_DB = yes

# Powerdns API key for DNS-01 ACME challenges
API_KEY            ?= $(shell openssl rand -hex 16; echo)

# Docker image name
IMAGE              ?= powerdnsadmin/pda-legacy

# Docker image tag
IMAGE_VER          ?= v0.4.1

# User who runs bootstrap code
PG_ADMIN           ?= $(PGUSER)

define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

PG_CONTAINER=$(PG_CONTAINER)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

test:
	curl -s -H 'X-API-Key: $(API_KEY)' $(HTTP_PROTO)://$(APP_SITE)/api/v1/servers/localhost/zones | jq '.'
